### ISSUE TITLE
启动失败，报错缺少simple_admin.sys_tasks数据库

### ISSUE THREAD

**Issue by franktrue** [suyuan32/simple-admin-job#2]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/10108380/231133990-a3a1f370-eb28-4c52-a426-baa04d686b57.png">
但初始化数据库需要启动simple-admin-job服务

**Comment by suyuan32** [comment]
直接启动，初始化，不用管报错先

**Comment by franktrue** [comment]
不行，初始化的时候报错![image](https://user-images.githubusercontent.com/10108380/231134874-175bf289-25ae-433e-a5fc-f8a81695e4a3.png)

**Comment by suyuan32** [comment]
检查配置，配置有问题， core enabled打开了吗？

**Comment by suyuan32** [comment]
查看log文件

**Comment by franktrue** [comment]
可以了，不好意思。core 里的jobrpc enabled没打开。感谢
